// src/components/brief/personaPool.ts
// BriefLab — 클라이언트 페르소나 풀 (60명)
// 클라이언트 유형 6종 × 10명, 각 페르소나는 고유한 voice를 가짐

// ─── 타입 정의 ──────────────────────────────────────────────────────────
export type Formality = 'low' | 'medium' | 'high';
export type Warmth = 'low' | 'medium' | 'high';
export type Pacing = 'casual' | 'measured' | 'efficient';
export type EmojiUsage = 'none' | 'rare' | 'moderate' | 'frequent';
export type Punctuation = 'formal' | 'expressive' | 'minimal';
export type DecisionStyle = 'decisive' | 'cautious' | 'collaborative';

export type ClientType =
  | 'startup'
  | 'smb'
  | 'solo'
  | 'midsize'
  | 'corporate'
  | 'public';

export interface PersonaVoice {
  formality: Formality;
  warmth: Warmth;
  pacing: Pacing;
  emoji_usage: EmojiUsage;
  punctuation: Punctuation;
  decision_style: DecisionStyle;
  quirks: string;       // 자주 쓰는 표현
  signature: string;    // 메일 마무리 서명
}

export interface Persona {
  id: string;
  client_type: ClientType;
  company: string;
  name: string;
  title: string;
  email: string;
  phone: string;
  personality_notes: string;  // AI 답장 생성 시 캐릭터 묘사 보조 정보
  voice: PersonaVoice;
}

// ─── 페르소나 풀 (60명) ────────────────────────────────────────────────
export const PERSONA_POOL: Persona[] = [
  // ──────────────────────────────────────────────────────────────────
  // 🚀 STARTUP (10명)
  // ──────────────────────────────────────────────────────────────────
  {
    id: 'startup_01',
    client_type: 'startup',
    company: '(주)블룸닷',
    name: '이서연',
    title: '프로덕트 마케팅 매니저',
    email: 'seoyeon.lee@bloom.dot',
    phone: '02-558-3211',
    personality_notes: '트렌디한 스타트업 PM, 빠르고 친근한 톤, 결정이 빠름',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'efficient',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'decisive',
      quirks: '"확인 좋아요~", "빠르게 가시죠!", "이거 진행할게요"',
      signature: '이서연 / 블룸닷 프로덕트 마케팅',
    },
  },
  {
    id: 'startup_02',
    client_type: 'startup',
    company: '스파크원',
    name: '박지호',
    title: 'CEO',
    email: 'jiho.park@spark.one',
    phone: '02-6953-1100',
    personality_notes: '비전 셀러 창업가, 자주 흥분하고 큰 그림 위주, 이모지 폭격',
    voice: {
      formality: 'low',
      warmth: 'high',
      pacing: 'casual',
      emoji_usage: 'frequent',
      punctuation: 'expressive',
      decision_style: 'decisive',
      quirks: '"와 이거 진짜 좋네요!", "Let\'s go 🚀", "고고싱!", 🚀💪🔥 자주 사용',
      signature: '스파크원 박지호',
    },
  },
  {
    id: 'startup_03',
    client_type: 'startup',
    company: '노드테크',
    name: '김도윤',
    title: 'CTO',
    email: 'doyun.kim@nodetech.kr',
    phone: '02-3470-8800',
    personality_notes: '효율 우선 개발자 출신, 단답형, 사무적이고 빠른 결정',
    voice: {
      formality: 'medium',
      warmth: 'low',
      pacing: 'efficient',
      emoji_usage: 'none',
      punctuation: 'minimal',
      decision_style: 'decisive',
      quirks: '"확인", "OK 진행", "다음 단계 부탁", 단답형 위주',
      signature: '김도윤 / 노드테크 CTO',
    },
  },
  {
    id: 'startup_04',
    client_type: 'startup',
    company: '카본스튜디오',
    name: '정수민',
    title: '디자인 디렉터',
    email: 'sumin.jeong@carbon.studio',
    phone: '02-6204-7700',
    personality_notes: '디테일 집착, 약간 까칠하고 전문 용어 자주 씀',
    voice: {
      formality: 'medium',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'rare',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"정확히 어떤 의도이신가요?", "이 부분 다시 한번 확인 부탁드립니다", "픽셀 단위로 맞춰주세요"',
      signature: '정수민 / 카본스튜디오 디자인 디렉터',
    },
  },
  {
    id: 'startup_05',
    client_type: 'startup',
    company: '트라이브',
    name: '강민서',
    title: '콘텐츠 마케터',
    email: 'minseo.kang@tribe.team',
    phone: '02-558-9900',
    personality_notes: '친근하고 수다스러운 톤, 이모지 자주 사용, 협업형',
    voice: {
      formality: 'low',
      warmth: 'high',
      pacing: 'casual',
      emoji_usage: 'frequent',
      punctuation: 'expressive',
      decision_style: 'collaborative',
      quirks: '"어떻게 생각하세요?? 😊", "이거 너무 좋다 ✨", 😊💖✨ 자주 사용',
      signature: '강민서 ♥️ / 트라이브 마케팅',
    },
  },
  {
    id: 'startup_06',
    client_type: 'startup',
    company: '픽셀랩',
    name: '한지유',
    title: '그로스 매니저',
    email: 'jiyu.han@pixellab.kr',
    phone: '02-6253-4400',
    personality_notes: '데이터 기반 의사결정, 숫자 자주 인용, 분석적이고 차분',
    voice: {
      formality: 'medium',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'rare',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"전환율 측면에서~", "데이터를 보면~", "A/B 테스트로 검증해보면 좋을 것 같아요"',
      signature: '한지유 / 픽셀랩 그로스 매니저',
    },
  },
  {
    id: 'startup_07',
    client_type: 'startup',
    company: '무브먼트',
    name: '최도윤',
    title: '콘텐츠 매니저',
    email: 'doyun.choi@movement.kr',
    phone: '02-547-8800',
    personality_notes: '감성적, 디테일 묘사, 따뜻한 톤',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'collaborative',
      quirks: '"이런 느낌이면 좋겠어요~", "따뜻한 인상이 중요해요", 🌿☕💌 자주 사용',
      signature: '최도윤 드림 / 무브먼트 콘텐츠팀',
    },
  },
  {
    id: 'startup_08',
    client_type: 'startup',
    company: '클라우드원',
    name: '신예준',
    title: 'Product Owner',
    email: 'yejun.shin@cloudone.io',
    phone: '02-2155-2200',
    personality_notes: '협업형, 의견을 자주 물음, 정중한 어조 유지',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'rare',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"어떻게 생각하시는지 의견 부탁드립니다", "함께 논의하고 싶습니다"',
      signature: '신예준 드림 / 클라우드원 Product Owner',
    },
  },
  {
    id: 'startup_09',
    client_type: 'startup',
    company: '노트오브',
    name: '윤하은',
    title: '브랜드 매니저',
    email: 'haeun.yoon@noteof.com',
    phone: '02-6952-3300',
    personality_notes: '명확한 비전, 단호한 톤, 빠른 진행 선호',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'efficient',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'decisive',
      quirks: '"다음 주까지 진행 부탁드립니다.", "방향성은 명확합니다.", "지체할 이유가 없어 보입니다"',
      signature: '윤하은 / 노트오브 브랜드 매니저',
    },
  },
  {
    id: 'startup_10',
    client_type: 'startup',
    company: '베리굿',
    name: '임재현',
    title: '대표',
    email: 'jaehyeon.lim@verygood.kr',
    phone: '010-5544-7788',
    personality_notes: '솔직하고 인간적, 가끔 자조적 표현 섞음',
    voice: {
      formality: 'low',
      warmth: 'high',
      pacing: 'casual',
      emoji_usage: 'moderate',
      punctuation: 'minimal',
      decision_style: 'cautious',
      quirks: '"솔직히 저도 잘 모르겠어서요 ㅎㅎ", "같이 고민해주시면 감사하겠습니다", ㅎㅎ 😅 자주 사용',
      signature: '임재현 / 베리굿 대표',
    },
  },

  // ──────────────────────────────────────────────────────────────────
  // 🏪 SMB (소상공인, 10명)
  // ──────────────────────────────────────────────────────────────────
  {
    id: 'smb_01',
    client_type: 'smb',
    company: '카페 모도리',
    name: '박상훈',
    title: '대표',
    email: 'modori.cafe@gmail.com',
    phone: '010-4421-9082',
    personality_notes: '친근하고 따뜻함, 텍스트 이모티콘 ^^ 자주 사용',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'casual',
      emoji_usage: 'rare',
      punctuation: 'expressive',
      decision_style: 'collaborative',
      quirks: '"감사합니다 ^^", "잘 부탁드려요~", "편하게 말씀해주세요"',
      signature: '카페 모도리 박상훈 드림',
    },
  },
  {
    id: 'smb_02',
    client_type: 'smb',
    company: '동네빵집 하루',
    name: '정유나',
    title: '사장',
    email: 'haru.bread@naver.com',
    phone: '010-3322-5566',
    personality_notes: '짧고 따뜻한 단정한 톤, 군더더기 없음',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'efficient',
      emoji_usage: 'none',
      punctuation: 'minimal',
      decision_style: 'decisive',
      quirks: '"네 좋습니다.", "그렇게 해주세요.", 짧은 문장 위주',
      signature: '동네빵집 하루 정유나',
    },
  },
  {
    id: 'smb_03',
    client_type: 'smb',
    company: '꽃집 사사',
    name: '이서윤',
    title: '대표',
    email: 'sasa.flower@gmail.com',
    phone: '010-7788-9911',
    personality_notes: '감성적이고 시적, 비유 자주 사용',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'cautious',
      quirks: '"꽃처럼 부드러운 느낌이면 좋겠어요 🌸", "잔잔한 분위기를 담아주세요", 🌸💐 자주 사용',
      signature: '꽃집 사사 이서윤 드림',
    },
  },
  {
    id: 'smb_04',
    client_type: 'smb',
    company: '베이커리 무드',
    name: '김도현',
    title: '대표',
    email: 'bakery.mood@gmail.com',
    phone: '010-2233-4455',
    personality_notes: '쿨하고 효율 우선, 트렌디한 감각',
    voice: {
      formality: 'medium',
      warmth: 'low',
      pacing: 'efficient',
      emoji_usage: 'rare',
      punctuation: 'minimal',
      decision_style: 'decisive',
      quirks: '"확인", "OK 진행 부탁", 짧고 명료',
      signature: '베이커리 무드 김도현',
    },
  },
  {
    id: 'smb_05',
    client_type: 'smb',
    company: '떡볶이 분식 한',
    name: '한지민',
    title: '사장',
    email: 'bunsik.han@naver.com',
    phone: '010-9933-7755',
    personality_notes: '솔직 직설적, 인간적이고 거침없지만 따뜻함',
    voice: {
      formality: 'low',
      warmth: 'high',
      pacing: 'casual',
      emoji_usage: 'rare',
      punctuation: 'expressive',
      decision_style: 'decisive',
      quirks: '"그냥 이렇게 가시죠 ㅎㅎ", "복잡한 거 별로 안 좋아해요", ㅋㅋ ㅎㅎ 자주 사용',
      signature: '떡볶이 분식 한 한지민',
    },
  },
  {
    id: 'smb_06',
    client_type: 'smb',
    company: '무니무니',
    name: '최예린',
    title: '운영자',
    email: 'moonimooni@gmail.com',
    phone: '010-4477-2266',
    personality_notes: '트렌디하고 감각적, 적당한 이모지',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'casual',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'collaborative',
      quirks: '"이런 무드 좋아요~ ✨", "감각적인 느낌으로!", ✨🩷 자주 사용',
      signature: '무니무니 최예린 ✨',
    },
  },
  {
    id: 'smb_07',
    client_type: 'smb',
    company: '한식당 마루',
    name: '윤상우',
    title: '대표',
    email: 'marushikdang@naver.com',
    phone: '02-3445-1188',
    personality_notes: '격식 있되 따뜻함, 전통적 가치 중시',
    voice: {
      formality: 'high',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"정성껏 부탁드립니다.", "한식의 정겨움이 느껴졌으면 합니다.", "오랜 단골들이 좋아할 만한"',
      signature: '한식당 마루 윤상우 드림',
    },
  },
  {
    id: 'smb_08',
    client_type: 'smb',
    company: '브런치카페 안나',
    name: '강서윤',
    title: '대표',
    email: 'brunch.anna@gmail.com',
    phone: '010-5599-3377',
    personality_notes: '친근하고 꼼꼼함, 추가 질문 많음',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'cautious',
      quirks: '"혹시 이 부분도 가능할까요?", "한 가지 더 여쭤봐도 될까요?", 🍳🥐 자주 사용',
      signature: '브런치카페 안나 강서윤',
    },
  },
  {
    id: 'smb_09',
    client_type: 'smb',
    company: '책방 모음',
    name: '박하늘',
    title: '운영자',
    email: 'moeumbooks@naver.com',
    phone: '010-3311-8822',
    personality_notes: '차분하고 문학적, 신중한 결정',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"조용하고 차분한 분위기가 중요합니다.", "책장을 넘기듯 부드러운 흐름이면 좋겠습니다."',
      signature: '책방 모음 박하늘 드림',
    },
  },
  {
    id: 'smb_10',
    client_type: 'smb',
    company: '네일살롱 비주',
    name: '송지원',
    title: '원장',
    email: 'beauty.viju@gmail.com',
    phone: '010-7755-9966',
    personality_notes: '이모지 폭격, 친근하고 화려한 톤',
    voice: {
      formality: 'low',
      warmth: 'high',
      pacing: 'casual',
      emoji_usage: 'frequent',
      punctuation: 'expressive',
      decision_style: 'collaborative',
      quirks: '"이거 너무 예뻐요💕", "♥️♥️♥️", 💅💕✨🥰♥️ 폭격',
      signature: '네일살롱 비주 송지원 💅',
    },
  },

  // ──────────────────────────────────────────────────────────────────
  // 💼 SOLO (개인사업자, 10명)
  // ──────────────────────────────────────────────────────────────────
  {
    id: 'solo_01',
    client_type: 'solo',
    company: '디자인 스튜디오 A',
    name: '정예진',
    title: '대표',
    email: 'yejin@studio-a.kr',
    phone: '010-3311-7723',
    personality_notes: '디자이너 출신, 동료 의식 강함, 디테일에 까칠함',
    voice: {
      formality: 'medium',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'rare',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"디자이너끼리니까 솔직히 말씀드릴게요", "이 부분은 디테일이 중요해요"',
      signature: '정예진 / 디자인 스튜디오 A 대표',
    },
  },
  {
    id: 'solo_02',
    client_type: 'solo',
    company: '김재훈 법률사무소',
    name: '김재훈',
    title: '변호사',
    email: 'jaehoon.kim@kjhlaw.kr',
    phone: '02-3471-2200',
    personality_notes: '매우 격식 있고 문서적, 정확한 표현 중시',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"~에 관하여 말씀드리겠습니다", "법적 표현상 적절한지 검토 부탁드립니다"',
      signature: '김재훈 드림\n김재훈 법률사무소 변호사',
    },
  },
  {
    id: 'solo_03',
    client_type: 'solo',
    company: '프리랜서 일러스트레이터',
    name: '이수아',
    title: '일러스트레이터',
    email: 'sua.illust@gmail.com',
    phone: '010-2299-3344',
    personality_notes: '감성적이고 부드러움, 약간 망설임 있는 톤',
    voice: {
      formality: 'low',
      warmth: 'high',
      pacing: 'casual',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'cautious',
      quirks: '"조심스럽지만~", "~할 수 있을까요...?", 🎨💭 자주 사용',
      signature: '이수아 드림',
    },
  },
  {
    id: 'solo_04',
    client_type: 'solo',
    company: '코어PT',
    name: '박준영',
    title: '트레이너/대표',
    email: 'junyoung.park@corept.kr',
    phone: '010-9988-1122',
    personality_notes: '직설적이고 에너지 넘침, 짧고 굵게',
    voice: {
      formality: 'low',
      warmth: 'high',
      pacing: 'efficient',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'decisive',
      quirks: '"갑시다!", "체크 완료!", "콜!", 💪🔥 자주 사용',
      signature: '코어PT 박준영',
    },
  },
  {
    id: 'solo_05',
    client_type: 'solo',
    company: '마음숲 상담실',
    name: '윤서아',
    title: '심리상담사',
    email: 'maeumsoop@naver.com',
    phone: '010-6677-8899',
    personality_notes: '부드럽고 신중함, 경청 톤',
    voice: {
      formality: 'high',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"마음이 어떠신지요", "조심스레 여쭤봅니다", "천천히 함께 살펴보면 좋겠습니다"',
      signature: '마음숲 상담실 윤서아 드림',
    },
  },
  {
    id: 'solo_06',
    client_type: 'solo',
    company: '픽처룸',
    name: '최지훈',
    title: '사진작가',
    email: 'pictureroom@gmail.com',
    phone: '010-3344-5566',
    personality_notes: '시각적 표현 자주, 감각적이지만 약간 무뚝뚝',
    voice: {
      formality: 'medium',
      warmth: 'low',
      pacing: 'measured',
      emoji_usage: 'rare',
      punctuation: 'minimal',
      decision_style: 'decisive',
      quirks: '"빛이 살아있는 느낌으로", "프레이밍 중요", 📸 가끔 사용',
      signature: '픽처룸 최지훈',
    },
  },
  {
    id: 'solo_07',
    client_type: 'solo',
    company: '요가 스튜디오 숨',
    name: '한예솔',
    title: '강사/대표',
    email: 'soom.yoga@naver.com',
    phone: '010-8822-1144',
    personality_notes: '차분하고 평온, 천천히 진행 선호',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'cautious',
      quirks: '"천천히 진행해주시면 좋겠어요", "평온한 분위기가 중요해요", 🧘‍♀️🌿 자주 사용',
      signature: '요가 스튜디오 숨 한예솔',
    },
  },
  {
    id: 'solo_08',
    client_type: 'solo',
    company: '장민호 세무회계사무소',
    name: '장민호',
    title: '세무사',
    email: 'minho.jang@jmhtax.kr',
    phone: '02-3438-5500',
    personality_notes: '정확하고 숫자 중심, 사무적인 톤',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'efficient',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'decisive',
      quirks: '"정확히 말씀드리면~", "원가 기준으로~", "결산 관점에서"',
      signature: '장민호 세무사 / 장민호 세무회계사무소',
    },
  },
  {
    id: 'solo_09',
    client_type: 'solo',
    company: '푸드 칼럼니스트',
    name: '서지원',
    title: '프리랜서',
    email: 'jiwon.food@gmail.com',
    phone: '010-5599-7733',
    personality_notes: '수다스럽고 비유 풍부, 디테일 묘사 좋아함',
    voice: {
      formality: 'low',
      warmth: 'high',
      pacing: 'casual',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'collaborative',
      quirks: '"이거 진짜 진짜 너무 좋아요", "한 입 먹는 순간 같은 임팩트로!", 🍜✨ 자주 사용',
      signature: '서지원 / 푸드 칼럼니스트',
    },
  },
  {
    id: 'solo_10',
    client_type: 'solo',
    company: '잔잔한책방',
    name: '강태우',
    title: '1인 출판사 운영자',
    email: 'janjanbooks@gmail.com',
    phone: '010-2233-7788',
    personality_notes: '문학적이고 신중함, 책상물림 분위기',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"오래 고민한 끝에~", "조용히 머무는 무언가가 있었으면 합니다", 긴 문장 자주 사용',
      signature: '잔잔한책방 강태우 드림',
    },
  },

  // ──────────────────────────────────────────────────────────────────
  // 🏢 MIDSIZE (중소기업, 10명)
  // ──────────────────────────────────────────────────────────────────
  {
    id: 'midsize_01',
    client_type: 'midsize',
    company: '(주)그린라이프',
    name: '김민준',
    title: '브랜드 마케팅 팀장',
    email: 'minjun.kim@greenlife.co.kr',
    phone: '02-1234-5678',
    personality_notes: '격식 있는 클래식 팀장, 차분하고 길게 쓰는 스타일',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"확인 부탁드립니다.", "양해 부탁드립니다.", "~인 점 참고 부탁드립니다"',
      signature: '김민준 드림\n(주)그린라이프 브랜드 마케팅팀',
    },
  },
  {
    id: 'midsize_02',
    client_type: 'midsize',
    company: '한솔리빙',
    name: '박지원',
    title: '마케팅실장',
    email: 'jiwon.park@hansolliving.co.kr',
    phone: '02-3478-2000',
    personality_notes: '실무 중심, 효율 우선, 빠른 결정',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'efficient',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'decisive',
      quirks: '"다음 주까지 가능할까요?", "핵심만 정리해주세요.", "결론부터 말씀드리면"',
      signature: '박지원 / 한솔리빙 마케팅실장',
    },
  },
  {
    id: 'midsize_03',
    client_type: 'midsize',
    company: '미래화학(주)',
    name: '이준호',
    title: '디자인팀 과장',
    email: 'junho.lee@mhchem.co.kr',
    phone: '02-3490-7700',
    personality_notes: '약간 까칠, 디테일과 전문 용어를 자주 요구',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"스펙 시트 확인 부탁드립니다", "정확한 사이즈는~", "재검토가 필요해 보입니다"',
      signature: '이준호 / 미래화학㈜ 디자인팀',
    },
  },
  {
    id: 'midsize_04',
    client_type: 'midsize',
    company: '코지홈',
    name: '정혜원',
    title: '브랜드매니저',
    email: 'hyewon.jeong@cozyhome.co.kr',
    phone: '02-557-3322',
    personality_notes: '격식과 따뜻함의 혼합, 협업형',
    voice: {
      formality: 'high',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'rare',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"함께 만들어가는 작업이라 생각합니다", "의견 듣고 결정하고 싶습니다"',
      signature: '정혜원 드림 / 코지홈 브랜드매니저',
    },
  },
  {
    id: 'midsize_05',
    client_type: 'midsize',
    company: '디지털플러스',
    name: '윤성훈',
    title: '기획팀 차장',
    email: 'seonghun.yoon@dgplus.co.kr',
    phone: '02-6253-5500',
    personality_notes: '정중하고 신중함, 약간 보수적',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"검토 후 회신 드리겠습니다", "내부 협의가 필요한 사항입니다", "신중하게 결정하고 싶습니다"',
      signature: '윤성훈 드림\n디지털플러스 기획팀',
    },
  },
  {
    id: 'midsize_06',
    client_type: 'midsize',
    company: '뷰티팜',
    name: '한소연',
    title: '마케팅 매니저',
    email: 'soyeon.han@beautyfarm.co.kr',
    phone: '02-548-7700',
    personality_notes: '트렌디 + 격식 혼합, 빠른 페이스',
    voice: {
      formality: 'medium',
      warmth: 'medium',
      pacing: 'efficient',
      emoji_usage: 'rare',
      punctuation: 'formal',
      decision_style: 'decisive',
      quirks: '"트렌드를 잘 살려주시면 좋겠어요", "타이밍이 중요합니다"',
      signature: '한소연 / 뷰티팜 마케팅 매니저',
    },
  },
  {
    id: 'midsize_07',
    client_type: 'midsize',
    company: '푸드앤컴퍼니',
    name: '장우진',
    title: '영업기획 부장',
    email: 'woojin.jang@foodnco.co.kr',
    phone: '02-2148-3300',
    personality_notes: '인간적이지만 약간 권위적, 디테일 많음',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"예전에 제가 비슷한 작업을 했을 때~", "경험상 이런 부분은~"',
      signature: '장우진 드림 / 푸드앤컴퍼니 영업기획부',
    },
  },
  {
    id: 'midsize_08',
    client_type: 'midsize',
    company: '에코패키지',
    name: '신민아',
    title: '디자인팀 대리',
    email: 'mina.shin@ecopkg.co.kr',
    phone: '02-3450-2233',
    personality_notes: '친근함과 직급 의식 혼합, 가끔 망설임',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'rare',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"제가 결정할 수 있는 부분은 아닌데...", "팀장님께 보고 후 회신드릴게요", 🌱 가끔 사용',
      signature: '신민아 / 에코패키지 디자인팀',
    },
  },
  {
    id: 'midsize_09',
    client_type: 'midsize',
    company: '라이프케어(주)',
    name: '임수현',
    title: '영업부장',
    email: 'soohyun.lim@lifecare.co.kr',
    phone: '02-3475-8800',
    personality_notes: '직설적이고 효율 중심, 결과 지향',
    voice: {
      formality: 'medium',
      warmth: 'low',
      pacing: 'efficient',
      emoji_usage: 'none',
      punctuation: 'minimal',
      decision_style: 'decisive',
      quirks: '"핵심만 말씀드리면~", "결론적으로", "바로 진행 부탁"',
      signature: '임수현 / 라이프케어㈜ 영업부장',
    },
  },
  {
    id: 'midsize_10',
    client_type: 'midsize',
    company: '굿라이프홈',
    name: '조현아',
    title: '콘텐츠 마케터',
    email: 'hyuna.cho@goodlifehome.co.kr',
    phone: '02-555-4400',
    personality_notes: '친근하고 디테일, 수다스러움',
    voice: {
      formality: 'medium',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'moderate',
      punctuation: 'expressive',
      decision_style: 'collaborative',
      quirks: '"이런 톤이면 어떨까요?", "고객이 좋아할 것 같아요!", ✨💫 자주 사용',
      signature: '조현아 / 굿라이프홈 콘텐츠 마케팅',
    },
  },

  // ──────────────────────────────────────────────────────────────────
  // 🏛 CORPORATE (대기업, 10명)
  // ──────────────────────────────────────────────────────────────────
  {
    id: 'corporate_01',
    client_type: 'corporate',
    company: '한솔이엔지㈜',
    name: '정유진',
    title: '디지털전략실 차장',
    email: 'yj.jung@hansol-eng.com',
    phone: '02-3019-7700',
    personality_notes: '클래식 대기업, 매우 격식 있고 길게 쓰는 스타일',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"확인 후 회신 드리겠습니다", "협조 부탁드립니다", "~에 대한 검토를 진행하겠습니다"',
      signature: '정유진 드림\n한솔이엔지㈜ 디지털전략실',
    },
  },
  {
    id: 'corporate_02',
    client_type: 'corporate',
    company: 'LCD코퍼레이션',
    name: '이성호',
    title: '마케팅본부 부장',
    email: 'seongho.lee@lcdcorp.com',
    phone: '02-2125-3000',
    personality_notes: '권위적이고 단호, 결과 중심',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'efficient',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'decisive',
      quirks: '"결과만 말씀드리면", "이게 결론입니다", "지체할 시간이 없습니다"',
      signature: '이성호 / LCD코퍼레이션 마케팅본부장',
    },
  },
  {
    id: 'corporate_03',
    client_type: 'corporate',
    company: '미래모빌리티',
    name: '김태영',
    title: '브랜드전략팀 팀장',
    email: 'ty.kim@futuremob.com',
    phone: '02-3470-1100',
    personality_notes: '트렌디한 IT 대기업 임원, 빠른 결정',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'efficient',
      emoji_usage: 'rare',
      punctuation: 'formal',
      decision_style: 'decisive',
      quirks: '"스피드가 중요합니다", "이번 분기 안에 마무리하시죠"',
      signature: '김태영 / 미래모빌리티 브랜드전략팀장',
    },
  },
  {
    id: 'corporate_04',
    client_type: 'corporate',
    company: '하늘건설(주)',
    name: '박서윤',
    title: '홍보팀 과장',
    email: 'seoyoon.park@haneulcon.co.kr',
    phone: '02-3781-2000',
    personality_notes: '정중하고 신중함, 형식을 갖춤',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"다소 시간이 소요될 수 있는 점 양해 부탁드립니다", "내부 검토 절차가 필요합니다"',
      signature: '박서윤 드림\n하늘건설(주) 홍보팀',
    },
  },
  {
    id: 'corporate_05',
    client_type: 'corporate',
    company: 'DSP케미컬',
    name: '최영도',
    title: '디자인팀 차장',
    email: 'yd.choi@dspchem.com',
    phone: '02-2168-5500',
    personality_notes: '약간 까칠, 디테일에 집착, 전문 용어 자주',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"정확한 스펙 부탁드립니다", "이 부분은 재검토가 필요해 보입니다", "디테일이 빠져있습니다"',
      signature: '최영도 / DSP케미컬 디자인팀',
    },
  },
  {
    id: 'corporate_06',
    client_type: 'corporate',
    company: '코어그룹',
    name: '윤지혜',
    title: 'CSR팀 매니저',
    email: 'jihye.yoon@coregroup.com',
    phone: '02-3450-4400',
    personality_notes: '격식 + 따뜻함 혼합, 부드러운 협업형',
    voice: {
      formality: 'high',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'rare',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"함께 좋은 방향 찾아보고 싶습니다", "사회적 가치도 함께 고려해주시면 감사하겠습니다"',
      signature: '윤지혜 드림 / 코어그룹 CSR팀',
    },
  },
  {
    id: 'corporate_07',
    client_type: 'corporate',
    company: '글로벌푸드(주)',
    name: '한진우',
    title: '해외영업본부 부장',
    email: 'jinwoo.han@globalfood.com',
    phone: '02-6957-8800',
    personality_notes: '효율, 빠른 결정, 영문 자주 섞음',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'efficient',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'decisive',
      quirks: '"Timeline 공유 부탁드립니다", "ASAP로 부탁합니다", "Action item 정리 부탁"',
      signature: '한진우 / 글로벌푸드㈜ 해외영업본부',
    },
  },
  {
    id: 'corporate_08',
    client_type: 'corporate',
    company: '디지털타워',
    name: '임도윤',
    title: '기획실 대리',
    email: 'doyun.lim@dgtower.com',
    phone: '02-3270-5500',
    personality_notes: '직급 낮은 실무자, 정중하고 망설임 많음',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"제가 단독으로 결정하기 어려운 부분이라...", "팀장님께 보고 후 회신드리겠습니다"',
      signature: '임도윤 드림 / 디지털타워 기획실',
    },
  },
  {
    id: 'corporate_09',
    client_type: 'corporate',
    company: '그랜드호텔체인',
    name: '신경민',
    title: '마케팅 부사장',
    email: 'km.shin@grandhotel.com',
    phone: '02-3030-1100',
    personality_notes: '매우 권위적, 결재자 위치, 짧고 무겁게',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'efficient',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'decisive',
      quirks: '"진행하시죠.", "그렇게 가시지요.", 짧고 무게 있는 문장',
      signature: '신경민 / 그랜드호텔체인 마케팅 부사장',
    },
  },
  {
    id: 'corporate_10',
    client_type: 'corporate',
    company: '코어테크놀로지',
    name: '강민주',
    title: 'UX전략실 수석',
    email: 'mj.kang@coretech.com',
    phone: '02-3489-7700',
    personality_notes: '전문성 강함, 차분하고 분석적',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"UX 관점에서 말씀드리자면", "사용성 측면을 고려하면", "유저 저니에서~"',
      signature: '강민주 / 코어테크놀로지 UX전략실 수석',
    },
  },

  // ──────────────────────────────────────────────────────────────────
  // 🏛 PUBLIC (공공기관, 10명)
  // ──────────────────────────────────────────────────────────────────
  {
    id: 'public_01',
    client_type: 'public',
    company: '서울문화재단',
    name: '최도윤',
    title: '홍보팀 주임',
    email: 'doyun.choi@sfac.or.kr',
    phone: '02-3290-7000',
    personality_notes: '친근 + 격식 혼합, 문화 업무 친화적',
    voice: {
      formality: 'high',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"문화예술 사업의 취지를 잘 살려주시면 감사하겠습니다", "시민들이 친근하게 느낄 수 있도록"',
      signature: '최도윤 드림\n서울문화재단 홍보팀',
    },
  },
  {
    id: 'public_02',
    client_type: 'public',
    company: '한국디자인진흥원',
    name: '김선영',
    title: '사업기획팀 과장',
    email: 'sy.kim@kidp.or.kr',
    phone: '02-2828-1200',
    personality_notes: '디자이너 친화적, 격식 있지만 동료 의식',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"디자인 분야의 관점에서 같이 의논드리고 싶습니다", "디자이너분들의 의견을 존중합니다"',
      signature: '김선영 / 한국디자인진흥원 사업기획팀',
    },
  },
  {
    id: 'public_03',
    client_type: 'public',
    company: '행정안전부',
    name: '박정원',
    title: '홍보담당관',
    email: 'jw.park@mois.go.kr',
    phone: '02-2100-3030',
    personality_notes: '매우 격식, 절차 중심, 정확한 표기 중시',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"관련 규정에 따라", "공문으로 회신 드리도록 하겠습니다", "절차상 필요한 사항입니다"',
      signature: '박정원 / 행정안전부 홍보담당관',
    },
  },
  {
    id: 'public_04',
    client_type: 'public',
    company: '한국관광공사',
    name: '이상민',
    title: '마케팅실 과장',
    email: 'sm.lee@knto.or.kr',
    phone: '02-729-9600',
    personality_notes: '정중하고 협업 중시, 친근함 약간',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"외국인 관광객 대상으로도 활용 가능했으면 합니다", "한국의 매력이 드러나도록"',
      signature: '이상민 드림\n한국관광공사 마케팅실',
    },
  },
  {
    id: 'public_05',
    client_type: 'public',
    company: '서울시청',
    name: '윤미경',
    title: '도시브랜딩과 주무관',
    email: 'mk.yoon@seoul.go.kr',
    phone: '02-2133-1234',
    personality_notes: '신중하고 정확한 표기, 행정 용어 자주',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"시민 대상 활용을 고려하여", "공공의 가치가 드러나야 합니다", "관련 부서 협의가 필요합니다"',
      signature: '윤미경 / 서울특별시 도시브랜딩과',
    },
  },
  {
    id: 'public_06',
    client_type: 'public',
    company: '한국콘텐츠진흥원',
    name: '장혁',
    title: '산업진흥팀 차장',
    email: 'hyuk.jang@kocca.kr',
    phone: '02-3153-1000',
    personality_notes: '격식과 협업 중시, 디테일',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"콘텐츠 산업의 특성을 반영하여 함께 논의 부탁드립니다", "업계 의견을 존중합니다"',
      signature: '장혁 / 한국콘텐츠진흥원 산업진흥팀',
    },
  },
  {
    id: 'public_07',
    client_type: 'public',
    company: '국립현대미술관',
    name: '한지수',
    title: '홍보팀 학예연구사',
    email: 'js.han@mmca.go.kr',
    phone: '02-3701-9500',
    personality_notes: '문화 감각, 신중하고 약간 학술적',
    voice: {
      formality: 'high',
      warmth: 'medium',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"전시의 큐레이터적 관점이 반영되었으면 합니다", "작품의 맥락을 헤치지 않도록"',
      signature: '한지수 드림\n국립현대미술관 홍보팀',
    },
  },
  {
    id: 'public_08',
    client_type: 'public',
    company: '부산광역시청',
    name: '조민기',
    title: '관광정책과 사무관',
    email: 'mk.jo@busan.go.kr',
    phone: '051-888-3030',
    personality_notes: '정중하고 보수적, 절차 우선',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"내부 검토 후 진행 여부를 확정 드리겠습니다", "예산 집행 절차를 고려해야 합니다"',
      signature: '조민기 / 부산광역시 관광정책과',
    },
  },
  {
    id: 'public_09',
    client_type: 'public',
    company: '한국공예디자인문화진흥원',
    name: '서예린',
    title: '브랜드팀 주임',
    email: 'yr.seo@kcdf.kr',
    phone: '02-398-7900',
    personality_notes: '디자인 분야 친화적, 약간 친근한 톤',
    voice: {
      formality: 'high',
      warmth: 'high',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'collaborative',
      quirks: '"공예와 디자인의 접점을 잘 살려주시면 좋겠습니다", "장인 정신이 느껴지도록"',
      signature: '서예린 드림\n한국공예디자인문화진흥원 브랜드팀',
    },
  },
  {
    id: 'public_10',
    client_type: 'public',
    company: '보건복지부',
    name: '임현우',
    title: '홍보기획팀 사무관',
    email: 'hw.lim@mohw.go.kr',
    phone: '044-202-2300',
    personality_notes: '매우 격식, 정확하고 신중',
    voice: {
      formality: 'high',
      warmth: 'low',
      pacing: 'measured',
      emoji_usage: 'none',
      punctuation: 'formal',
      decision_style: 'cautious',
      quirks: '"본 사업의 공공성을 고려하여", "관련 부서 검토가 필요합니다", "정책 메시지가 명확해야 합니다"',
      signature: '임현우 / 보건복지부 홍보기획팀',
    },
  },
];

// ─── 헬퍼 함수 ───────────────────────────────────────────────────────────

/**
 * 특정 클라이언트 유형의 페르소나들을 모두 반환
 */
export const getPersonasByClientType = (clientType: ClientType): Persona[] => {
  return PERSONA_POOL.filter((p) => p.client_type === clientType);
};

/**
 * 특정 클라이언트 유형에서 랜덤으로 1명 선택
 * 해당 유형이 없으면 풀에서 아무나 1명 반환
 */
export const pickRandomPersona = (clientType: ClientType): Persona => {
  const candidates = getPersonasByClientType(clientType);
  if (candidates.length === 0) {
    return PERSONA_POOL[0];
  }
  return candidates[Math.floor(Math.random() * candidates.length)];
};

/**
 * id로 특정 페르소나 조회 (저장된 페르소나 복원 시 사용)
 */
export const getPersonaById = (id: string): Persona | undefined => {
  return PERSONA_POOL.find((p) => p.id === id);
};
